from django.apps import AppConfig

class QuizConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'quiz'

    def ready(self):
        import quiz.signals
        from .models import EmojiMovieDatabase
        movies = [
            ("The Lion King", "🦁👑"),
            ("Titanic", "🚢💔❄️"),
            ("The Lord of the Rings", "🧙‍♂️💍🔥"),
            ("Harry Potter", "⚡🧙‍♂️🦉"),
            ("Spider-Man", "🕷️🧑‍🦰"),
            ("The Dark Knight", "🦇🃏🌃"),
            ("Inception", "🧠💤🔫"),
            ("E.T.", "👽📞🏠"),
            ("Interstellar", "👨‍🚀🌌⏳"),
            ("The Terminator", "🤖🔫🕶️"),
            ("Jurassic Park", "🦖🌴💥"),
            ("Toy Story", "🧒🪀🚀"),
            ("Up", "🎈🏠👴"),
            ("Finding Nemo", "🐠🔍🌊"),
            ("Kung Fu Panda", "🐼🥋👊"),
            ("Ratatouille", "🧑‍🍳🐀🥘"),
            ("Aladdin", "🧞‍♂️🕌🧒"),
            ("Frozen", "👩‍❄️❄️⛄"),
            ("Bohemian Rhapsody", "💄🎤👑"),
            ("World War Z", "🧟‍♂️🔫🌍"),
            ("Captain America", "🦸‍♂️🛡️"),
            ("The Hobbit", "🧔⚔️🐉"),
            ("Snow White", "👑👸🪞"),
            ("The Chronicles of Narnia", "🧙‍♂️🦁🗡️"),
            ("Dumbo", "🐘👂🎪"),
            ("Cars", "🚗🏎️💨"),
            ("Sherlock Holmes", "🕵️‍♂️🔍🇬🇧"),
            ("The Incredible Hulk", "😡🔩🟩"),
            ("Twilight", "🧛‍♂️🩸🌕"),
            ("Psycho", "🧑🔪🛁"),
            ("Ghostbusters", "👻🚫🔋"),
            ("V for Vendetta", "🎭💣🗽"),
            ("Hocus Pocus", "🧙‍♀️🧹🐱"),
            ("Cinderella", "👩🪞🧵🐭"),
            ("Zombieland", "🧟‍♂️🧠🏃‍♂️"),
            ("The Prestige", "🎩🪄🎭"),
            ("Charlotte's Web", "🐷👧🌾"),
            ("The Matrix", "💻👓🕶️"),
            ("Coraline", "🧒👹🪵"),
            ("The Pursuit of Happyness", "👨‍👦💰💼"),
            ("The Hunger Games", "🕊️🔥🏹"),
            ("Indiana Jones", "🐍🧑‍🏫⚰️"),
            ("Beauty and the Beast", "👸🌹🫖��️"),
            ("Dead Poets Society", "👨‍🏫📚👩‍🎓"),
            ("Babe", "🐷🐮🐔🚜"),
            ("Home Alone", "🎄👦🎁🎅"),
            ("The Polar Express", "🎄🚂❄️"),
            ("Aladdin", "👸🧞‍♂️🐯"),
            ("Planet of the Apes", "🐵🧠🌍"),
            ("The Blind Side", "🧤🏈👩"),
            ("Limitless", "🧠💊⏳"),
            ("Space Jam", "🏀🐰👽"),
            ("Snakes on a Plane", "🐍✈️😱"),
            ("Madagascar", "🦁🦓🦒✈️"),
            ("Top Gun", "👨‍✈️✈️🕶️"),
            ("Blade", "🧛‍♂️🕶️🗡️"),
            ("Winnie the Pooh", "🐻🍯🌲"),
            ("Charlotte's Web", "🕸️👧🐖"),
            ("Elvis", "🎤🕺👞"),
            ("Matilda", "👧📖👹"),
            ("Big Hero 6", "🤖👦❤️"),
            ("Wonder Woman", "🦸‍♀️🛡️🌍"),
            ("Burnt", "👨‍🍳🔥🍝"),
            ("Inside Out", "🧠🫀😢"),
            ("The Princess Diaries", "👑🧒🏰"),
            ("Alice in Wonderland", "🐰🕳️⏱️"),
            ("Rocketman", "🎤👨‍🎤🎶"),
            ("The Devil Wears Prada", "��👠👠"),
            ("Spider-Man", "🏙️��️🕶️"),
            ("A Star is Born", "🧑‍🎤🌟🎤"),
            ("La La Land", "🎬👩‍🎤💔"),
            ("Dirty Dancing", "💃🏽🕺🎵"),
            ("Saving Private Ryan", "🪖⛴️🩸"),
            ("12 Angry Men", "👨‍⚖️🏛️🧔"),
            ("The Wolf of Wall Street", "💼💰🔫"),
            ("Boss Baby", "👶🕶️🔫"),
            ("The Greatest Showman", "🧒🎩🎪✨"),
            ("Life of Pi", "🐯⛵🌊"),
            ("Lucy", "👩🧠⚡"),
            ("Death Note", "🔍📓💀"),
            ("Legally Blonde", "🎓💬📚"),
            ("Finding Dory", "👨‍⚕️🦷🪥"),
            ("I Am Legend", "🧟‍♂️🏙️🌇"),
            ("The Revenant", "🏞️🐻🚶"),
            ("Charlie and the Chocolate Factory", "🎩🧒🍫"),
            ("Teenage Mutant Ninja Turtles", "🐢🍕🏙️"),
            ("Monsters, Inc.", "🐾🎮🚪"),
            ("Flubber", "🔮👨‍🔬⚗️"),
            ("Morbius", "🕷️⚡🧛‍♂️"),
            ("Fast & Furious", "🏎️👊🛣️"),
            ("Wish Dragon", "🧞‍♂️🎤🎙️"),
            ("Lemony Snicket", "🧒📕🧛‍♂️"),
            ("Back to the Future", "🕶️🎸🌌"),
            ("The Lion King (Broadway)", "🎭🦁🗺️"),
            ("Letters to Juliet", "💬🕊️📃"),
            ("The Sound of Music", "🎵🐑🌄"),
            ("Lady and the Tramp", "🍝🐶❤️"),
            ("Peter Pan", "🧚🧒🧚‍♀️"),
            ("Warm Bodies", "🧟‍♂️📓🧟‍♀️"),
            ("The Secret Life of Walter Mitty", "📷🎞️👨‍🎓"),
        ]
        for title, emoji in movies:
            if not EmojiMovieDatabase.objects.filter(title=title, emoji_representation=emoji).exists():
                EmojiMovieDatabase.objects.create(title=title, emoji_representation=emoji)
