# Generated by Django 5.2.1 on 2025-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_emojimovie_emojimoviedatabase_player_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_login',
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
